name: Build and Deploy

on:
  push:
    tags:
      - prod-v.*
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BUILD_ARGS: |
    "TAG=$CHANGE_ME"

jobs:
  build:
    name: Build
    runs-on: ${CHANGE_ME}
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Get repository name
      id: repo-name
      uses: MariachiBear/get-repo-name-action@v1.2.0
      with:
        with-owner: 'true'
        string-case: 'lowercase'
    - name: Build container and push to registry
      uses: docker/build-push-action@v5
      with:
        file: .docker/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ steps.repo-name.outputs.repository-name }}:${{ github.sha }}
        build-args: ${{ env.BUILD_ARGS }}

